#  **<font color= Indigo> Intro Python** : 


## **<font color = Khaki> Iníciando na linguagem**

### <font color= Khaki> **PRINT()**


In [1]:
import numpy as np

# Suponha que você tenha três arrays a, b e c
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# Empilhamento vertical
result_vertical = np.vstack((a, b, c))

# Empilhamento horizontal
result_horizontal = np.hstack((a, b, c))

print("Empilhamento Vertical:\n", result_vertical)
print("Empilhamento Horizontal:", result_horizontal)


Empilhamento Vertical:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Empilhamento Horizontal: [1 2 3 4 5 6 7 8 9]


In [2]:
import numpy as np

# Suponha que você tenha três arrays a, b e c
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# Combinação horizontal (ao longo das colunas)
result_horizontal = np.concatenate((a, b, c))

# Combinação vertical (ao longo das linhas)
result_vertical = np.concatenate((a, b, c), axis=None)

print("Combinação Horizontal:", result_horizontal)
print("Combinação Vertical:", result_vertical)


Combinação Horizontal: [1 2 3 4 5 6 7 8 9]
Combinação Vertical: [1 2 3 4 5 6 7 8 9]


In [14]:
print("Hello Wolrd")
print(10)
print("Ike", 18)

Hello Wolrd
10
Ike 18



### **<font color= SandyBrown>Desafios com Print( )**

**Questão 1**

Imprima a frase: "Escola de Dados da Alura!".



In [15]:
print("Escola de Dados Alura!")

Escola de Dados Alura!


**Questão 2**

Imprima na tela seu nome e seu sobrenome seguindo a estrutura abaixo:



In [16]:
print("Nome: Ike Gabriel")
print("Sobrenome: Rodrigues de Kenard")


Nome: Ike Gabriel
Sobrenome: Rodrigues de Kenard


**Questão 3**

Imprima o seu primeiro nome letra a letra. Por exemplo, nome é Mirla, então eu obtenho a seguinte saída:

M

I

R

L

A




In [17]:
print("I", "K","E",sep="\n")


I
K
E


**Questão 4**

Imprima o dia do seu nascimento em formato dia mês ano. Os valores de dia e ano não podem estar entre aspas. O formato deve estar como no exemplo, supondo uma data de aniversário dia 28 de fevereiro de 2003:




In [18]:
#Normal
print("26","de junho de",2005)

26 de junho de 2005


In [19]:
#Usando Biblioteca Data time
from datetime import datetime, date

dt = datetime.strptime("26/06/05", "%d/%m/%y")
dt.strftime("%d. %B %Y")


'26. June 2005'

**Questão 5**



Imprima em um único print o atual ano que você está fazendo esse curso, o valor do ano deve ser um dado numérico. A saída do print deve ser a seguinte:


          Ano atual: [ano]


In [20]:
#Normal
print("Ano atual: 2023")

Ano atual: 2023


In [21]:
#Usando Biblioteca Data time
import datetime

hoje = datetime.date.today()

#acessando o atributo ano
ano = hoje.year
print("Ano atual:", ano)

#usando o metódo .now e strtime
ano2 = datetime.datetime.now().strftime('%Y')

print("Ano atual:", ano2)


Ano atual: 2023
Ano atual: 2023


## **<font color= cyan>Manipulando Dados**

### **Coleta e amostragem de dados**


**Questão 1** 

Crie um programa que solicite à pessoa usuária digitar seu nome, e imprima “Olá, [nome]!”.

In [22]:
nome = input("Por favor informe seu nome: ")
print("Olá", nome)

Olá 


**Quetão 2**


Crie um programa que solicite à pessoa usuária digitar seu nome e idade, e imprima “Olá, [nome], você tem [idade] anos.”.


In [6]:

nome = input("Olá, por favor insira seu nome: ")
idade = int(input("Por favor tambem informe a sua idade: "))
print(f"Olá, {nome} você tem {idade} anos")

Olá, ike você tem 10, anos


**Questão 3**

Crie um programa que solicite à pessoa usuária digitar seu nome, idade e altura em metros, e imprima “Olá, [nome], você tem [idade] anos e mede [altura] metros!”.


In [ ]:

nome = input("Olá, por favor insira seu nome: ")
idade = int(input("Por favor tambem informe a sua idade: "))
altura = float(input("Digite sua altura em metros:"))
print(f"Olá, {nome} você tem {idade} anos e mede {altura} metros ")

Olá, ike você tem 18 anos e mede 1.75 metros 


### **Calculadora com operadores**


**Questão 1**

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a soma dos dois valores.


In [ ]:
#Soma
print("=== Realize uma soma ===\n")

num1 = float(input("Insira um valor"))
num2 = float(input("Insira outro valor"))
soma = num1 + num2
print(f'A soma dos valores descritos é igual a: {soma}')

A soma dos valores descritos é igual a: 61.6


**Questão 2**

Crie um programa que solicite três valores numéricos à pessoa usuária e imprima a soma dos três valores.


In [ ]:
#Soma
print("=== Realize uma soma ===\n")

num1 = float(input("Insira um valor decimal"))
num2 = int(input("Insira um valor inteiro"))
num3 = int(input("Insira outro valor inteiro"))

soma = num1 + num2 + num3
print(f'A soma dos valores descritos é igual a: {soma}')

**Questão 3**

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a subtração do primeiro pelo o segundo valor.


In [12]:
#Subtração
print("=== Realize uma subtração ===\n")

num1 = float(input("Insira um valor"))
num2 = float(input("Insira outro valor"))
sub = num1 - num2
print(f'A soma dos valores descritos é igual a: {sub}')

A soma dos valores descritos é igual a: 3.0


**Questão 4**

Crie um programa que solicite dois valores numéricos à pessoa usuária e imprima a multiplicação dos dois valores.

In [13]:
#Multiplicação
print("=== Realize uma multiplicação ===\n")

num1 = float(input("Insira um valor"))
num2 = float(input("Insira outro valor"))
mult = num1 * num2
print(f'A soma dos valores descritos é igual a: {mult}')

A soma dos valores descritos é igual a: 3.0


**Questão 5**

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e realize a divisão entre os dois valores.

 Deixe claro que o valor do denominador não pode ser 0.



In [25]:
#Divisão
print("=== Realize uma divisão ===\n")
print("Não se esqueça o denomindador deve ser diefernete de 0\n")

num1 = float(input("Insira um valor para ser o numerador"))
num2 = float(input("Insira outro valor para ser o denominador"))
div = num1 / num2

print(f'A soma dos valores descritos é igual a: {div}')

===Realize uma divisão===

Não se esqueça o denomindador deve ser diefernete de 0

A soma dos valores descritos é igual a: 2.5


**Questão 6**

Crie um programa que solicite dois valores numéricos, um operador e uma potência, e realize a exponenciação entre esses dois valores.


In [ ]:
#Potenciação
print("=== Realize uma potenciação ===\n")

num1 = float(input("Insira um valor"))
num2 = float(input("Insira outro valor"))
expo = num1 ** num2

print(f'A soma dos valores descritos é igual a: {expo}')

**Questão 7**

Crie um programa que solicite dois valores numéricos, um numerador e um denominador e realize a divisão inteira entre os dois valores.

 Deixe claro que o valor do denominador não pode ser 0.


In [24]:
#Divisão c/Inteiros
print("=== Realize uma divisão com números inteiros ===\n")
print("Não se esqueça o denomindador deve ser diefernete de 0\n")

num1 = int(input("Insira um valor para ser o numerador"))
num2 = int(input("Insira outro valor para ser o denominador"))
div = num1 // num2

print(f'A soma dos valores descritos é igual a: {div}')

===Realize uma divisão com números inteiros===

Não se esqueça o denomindador deve ser diefernete de 0

A soma dos valores descritos é igual a: 2


**Questão 8**

Crie um programa que solicite dois valores numéricos, um numerador e um denominador, e retorne o resto da divisão entre os dois valores.

 Deixe claro que o valor do denominador não pode ser 0.


In [26]:
#Resto divisão
print("=== Encontre o resultado do resto da divisão ===\n")
print("Não se esqueça o denomindador deve ser diefernete de 0\n")

num1 = int(input("Insira um valor para ser o numerador"))
num2 = int(input("Insira outro valor para ser o denominador"))
div = num1 % num2

print(f'A soma dos valores descritos é igual a: {div}')

===Encontre o resultado do resto da divisão===

Não se esqueça o denomindador deve ser diefernete de 0

A soma dos valores descritos é igual a: 1


**Questão 9**

Crie um código que solicita 3 notas de um estudante e imprima a média das notas.


In [36]:
#Média das notas de um estudante
print("=== Calcule aqui a sua media ===")

nota1 = float(input("Informe qual foi a sua 1° nota: "))
nota2 = float(input("Informe qual foi a sua 2° nota: "))
nota3 = float(input("Informe qual foi a sua 3° nota: "))

med= nota1+nota2 +nota3/3


print(f'A sua média foi igual a %.2f' %(med))

=== Calcule aqui a sua media ===
A sua média foi igual a 10.67


**Questão 10**

Crie um código que calcule e imprima a média ponderada dos números 5, 12, 20 e 15 com pesos respectivamente iguais a 1, 2, 3 e 4.

In [37]:
#Média ponderada
print((5*1)+(12*2)+(20*3)+(15*4)/(1 + 2 + 3 + 4))

95.0


### **Editando textos**

**Questão 1**

Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase na tela.


In [41]:
frase = " Ninguém nunca vai lhe contar\n Quando você quiser saber o motivo \n Eles apenas dizem que você agora está só\n Enchem a sua cabeça com mentiras\n"
print(frase)

 Ninguém nunca vai lhe contar
 Quando você quiser saber o motivo 
 Eles apenas dizem que você agora está só
 Enchem a sua cabeça com mentiras



**Questão 2**

Crie um código que solicite uma frase e depois imprima a frase na tela.


In [43]:
frase = input("Insira uma frase para que seja impressa")
print(frase)

Loud campeã do champions


**Questão 3**

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras maiúsculas.


In [44]:
frase = input("Insira uma frase para que seja impressa").upper()
print(frase)

IKE LINDO


**Questão 4**

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase digitada mas com todas as letras minúsculas.


In [1]:
frase = input("Insira uma frase para que seja impressa").lower()
print(frase)

loko


**Questão 5**

Crie uma variável chamada “frase” e atribua a ela uma string de sua escolha. Em seguida, imprima a frase sem espaços em branco no início e no fim.


In [2]:
frase = input("Insira uma frase para que seja impressa")
frase.strip()

iek


**Questão 6**

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim.

In [ ]:
frase = input("Insira uma frase para que seja impressa").strip()
print(frase)

**Questão 7**

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase sem espaços em branco no início e no fim e em letras minúsculas.


In [ ]:
frase = input("Insira uma frase para que seja impressa").strip().lower()
print(frase)

**Questão 8**

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “e” trocadas pela letra “f”.


In [3]:
frase = input("Insira uma frase para que seja impressa").replace('e', 'f')
print(frase)

flffantf


**Questão 9**

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as vogais “a” trocadas pela caractere “@”.

In [4]:
frase = input("Insira uma frase para que seja impressa").replace('a', '@')
print(frase)

@b@c@te


**Questão 10**

Crie um código que solicite uma frase à pessoa usuária e imprima a mesma frase com todas as consoantes “s” trocadas pelo caractere “$”.


In [5]:
frase = input("Insira uma frase para que seja impressa").replace('s', '$')
print(frase)

$exta-feira


 # <font color= darkmagenta> **Estrutura Condicional**

ㅤ<font color = DeepPink>
* ###  **if:**
* ###  **Elif:**
* ### **Else:**

In [ ]:
media = float("Insira sua média: ")

if media >= 6.0:             #Se x faça isso
  print("Aprovado(a)")
elif 6.0 > media >= 4.0:     #Caso y faça outra coisa
  print("Recuperação")
else:                        #Caso z faça alguma outra coisa
  print("Reprovado(a)")


### **Aquecendo na programação**

**Questão 1**

Escreva um programa que peça à pessoa usuária para fornecer dois números e exibir o número maior.

=== |Véja qual número é maio| ===

O segundo número é o maior sendo ele: 8.0


**Questão 2**

Escreva um programa que solicite o percentual de crescimento de produção de uma empresa e informe se houve um crescimento (porcentagem positiva) ou decrescimento (porcentagem negativa).

|Véja qual número é maio|

Não houve crescimento nenhum


**Questão 3**

Escreva um programa que determine se uma letra fornecida pela pessoa usuária é uma vogal ou consoante

In [40]:

letra = input("Insira uma letra para saber se ela é vogal ou consoante: ").lower()
if letra == 'a':
    print("A letra é uma vogal")
elif letra == 'e':
    print("A letra é uma vogal")
elif letra == 'i':
    print("A letra é uma vogal")
elif letra == 'o':
    print("A letra é uma vogal")
elif letra == 'u':
    print("A letra é uma vogal")
else:
    print("A letra é uma consoante")

A letra é uma consoante


**Questão **

**Questão **

**Questão **

**Questão **

**Questão **

**Questão **

**Questão **

**Questão **